Fix building with MSYS2 distributed MinGW hdf5.
aldanor/hdf5-rust pull request #229
Opened 2023-01-26 12:39 UTC by Berrysoft

* Allow minor version to be 14, because the version of MSYS2 distributed MinGW hdf5 is 1.14.
* Add `is_msvc` to `build.rs` to determine target enviroment from env var instead of `cfg!`, to make cross-compile right. Here the term "cross-compile" also means targeting GNU with MSVC toolchain (which is very common).
* The dll name of hdf5 is `libhdf5-0.dll`. I've noticed this commit: https://github.com/msys2/MINGW-packages/commit/205f329c0231d8046b8bb3a2f6dff787c6613347 . It may change the dll name and I'll update if so.
* Limit `msvc_dll_indirection` to MSVC only.
* The tests have passed on my machine with MSVC toolchain, targeting GNU, and latest MSYS2.

2023-01-27 08:09 UTC, mulimoen commented
Do you have a way of including this build in the CI?

2023-01-27 08:14 UTC, Berrysoft commented
I will try to include it. And by the way, `cargo-clippy` fails because of `uninlined_format_args`. Maybe you need to turn it off because it's very annoying:)

2023-01-27 08:28 UTC, Berrysoft commented
@mulimoen I've added a job to test this crate with MSYS2.

2023-01-27 08:30 UTC, mulimoen commented
The clippy lints should be fixed in a separate PR, I think clippy supports `rust_version` which would prevent MSRV trouble in the future. We need a bump in MSRV for that...

2023-01-27 08:47 UTC, Berrysoft commented
The package updated just now, and the dll name now changes with the soversion. Should we use `pkgconf` in that case, instead of hard-coding the dll name manually?

2023-01-27 09:05 UTC, Berrysoft commented
The new test passed.

2023-01-27 09:11 UTC, mulimoen commented
I have not used a windows system in ages. I think you are a better judge of whether `pkgconf` will be more or less suprising for the developers using this library

2023-01-27 09:19 UTC, Berrysoft commented
MSYS2 provides `pkgconf` of course, and `vcpkg`, the Microsoft-banded C/C++ package manager, [also provides](https://github.com/microsoft/vcpkg/tree/master/ports/pkgconf) `pkgconf` affairs. I have also noticed that some other bindings, for example, [libgit2](https://github.com/rust-lang/git2-rs/blob/master/libgit2-sys/build.rs) and [openssl](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build/find_normal.rs) also use `pkgconf` to find libs.

`openssl-sys` only uses `pkgconf` for Windows GNU target. I think I can follow this approach.

2023-01-27 10:14 UTC, Berrysoft commented
I added pkg-config support for all windows target because the gnu and msvc targets all supports pkg-config, and (maybe a bug?) they cannot be dealt separately. (When targeting GNU, a MSVC target build script will also be built and executed.)

And for Windows target, I choose to trust pkg-config result and not checking the dll, because at first we wanted to avoid hard-coding the dll names with pkg-config, which could not provide the dll name either.

2023-01-27 10:23 UTC, mulimoen commented
We know hdf5 localisation is difficult, especially on windows. Thanks a lot for doing this the proper way

2023-01-28 03:18 UTC, Berrysoft commented
Pkg-config for Windows support added. Now it should work with pkg-config, and if pkg-config is not installed, `HDF5_DIR` would also work (if dll name hadn't been changed by MSYS2).

`pkg-config` gives many paths like `C:\msys64\mingw64\lib\..\bin`, so we need to canonicalize the path before querying it in `PATH`. The paths in `PATH` should also be canonicalized when comparing because `canonicalize` would turn a path to a UNC path on Windows.

2023-01-31 19:50 UTC, mulimoen requested changes
Just some minor comments, otherwise this PR is in great shape. Would you mind adding to the changelog?

2023-02-07 03:04 UTC, Berrysoft commented on hdf5-sys/build.rs
> +        let re = Regex::new(r"^(1)\.(8|10|12|13|14)\.(\d\d?)(_\d+)?(-patch\d+)?$").ok()?;
I'm waiting for #227 merge.

2023-02-07 03:11 UTC, Berrysoft commented on hdf5-sys/build.rs
> +            std::env::set_var("PKG_CONFIG_ALLOW_CROSS", "1");
Reference: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build/find_normal.rs#L205-L207

At least openssl-sys doesn't reset this variable:)

This variable may cause some mismatching when there are many `pkg-config` installed on one system in particular cases (for example, MinGW `pkg-config` is called when using MSVC toolchain), but the user can avoid that by setting `PKG_CONFIG_PATH` manually.

2023-02-07 06:41 UTC, mulimoen commented on hdf5-sys/build.rs
> +            std::env::set_var("PKG_CONFIG_ALLOW_CROSS", "1");
Great, thanks for clarifying!

2023-02-08 05:21 UTC, mulimoen approved these changes

2023-06-09 18:32 UTC, aldanor commented
If there's still interest in moving this forward, it would have to be rebased on the latest master, now that 1.14 support is in and all the build failures etc have been hopefully resolved and fixed.

2023-06-10 06:03 UTC, Berrysoft commented
I've merged master but need approval to run CI.

2023-06-10 11:19 UTC, aldanor commented
@Berrysoft There's changelog conflicts so you might want to quickly rebase again.

It looks like your build ran on CI and failed: https://github.com/aldanor/hdf5-rust/actions/runs/5227987760/jobs/9440874079?pr=229

Because the version is `1.14.1.2` (I think we do parse `1.14.1-2`, like it looks on arch, but not this format)

2023-06-10 11:24 UTC, Berrysoft commented
I solved the conflicts and updated the regex. Now it should parse both kind of versions.

2023-06-10 11:47 UTC, aldanor commented
@mulimoen Looks good? Any comments from your side? Seems like mingw build now runs green again 1.14.1.2.

// @Berrysoft not to be picky, minor nit: in PRs you'd normally _rebase_ your branch against the main one as opposed to merging, otherwise you end up with all those merge commits in main. No big deal though, I'll just squash-merge it.

2023-06-10 11:48 UTC, aldanor commented
Interestingly enough, this mingw run doesn't hit this problem https://github.com/HDFGroup/hdf5/issues/3091

2023-06-10 11:55 UTC, Berrysoft commented
I cannot reproduce this problem on my device either.

2023-06-10 19:27 UTC, mulimoen commented
Weird with the 1.14.1-2 static build, can't see any obvious differences in the build flags. Looks good to go!

2023-06-10 21:17 UTC, merged

2023-06-10 21:17 UTC, aldanor commented
Now merged, thanks @Berrysoft